# Generated by Django 5.2.6 on 2025-11-18 17:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('licensed_users', models.PositiveIntegerField(default=1, help_text='Number of user licenses purchased')),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Monthly rate in USD', max_digits=10)),
                ('billing_cycle_type', models.CharField(choices=[('monthly', 'Monthly'), ('anniversary', 'Anniversary'), ('custom', 'Custom')], default='monthly', help_text='Type of billing cycle', max_length=20)),
                ('billing_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for anniversary billing (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('contract_start_date', models.DateField(help_text='Contract start date')),
                ('contract_end_date', models.DateField(blank=True, help_text='Contract end date (null for ongoing)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(help_text='Organization this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='court_rules.organization')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_period_start', models.DateField(help_text='Start of billing period')),
                ('billing_period_end', models.DateField(help_text='End of billing period')),
                ('amount_billed', models.DecimalField(decimal_places=2, help_text='Total amount billed in USD', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid in USD', max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, help_text='Balance due in USD', max_digits=10)),
                ('invoice_date', models.DateField(blank=True, help_text='Date invoice was generated', null=True)),
                ('payment_received_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('payment_due_date', models.DateField(blank=True, help_text='Date payment is due', null=True)),
                ('payment_cleared_date', models.DateField(blank=True, help_text='Date payment cleared', null=True)),
                ('reminder_sent_date', models.DateField(blank=True, help_text='Date reminder was sent', null=True)),
                ('custom_date_1', models.DateField(blank=True, help_text='Custom date field 1', null=True)),
                ('custom_date_2', models.DateField(blank=True, help_text='Custom date field 2', null=True)),
                ('custom_date_3', models.DateField(blank=True, help_text='Custom date field 3', null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partially_paid', 'Partially Paid'), ('cleared', 'Cleared'), ('refunded', 'Refunded'), ('placeholder_1', 'Custom Status 1'), ('placeholder_2', 'Custom Status 2')], default='pending', help_text='Current payment status', max_length=20)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number or reference', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this billing record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(help_text='Subscription being billed', on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='court_rules.subscription')),
            ],
            options={
                'db_table': 'billing_records',
                'ordering': ['-billing_period_start'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('license_change', 'License Count Changed'), ('price_change', 'Price Changed'), ('status_change', 'Status Changed'), ('cycle_change', 'Billing Cycle Changed'), ('contract_change', 'Contract Terms Changed')], help_text='Type of change', max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON or string)')),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON or string)')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change')),
                ('effective_date', models.DateField(blank=True, help_text='Date when change becomes effective', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(help_text='Subscription being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='court_rules.subscription')),
            ],
            options={
                'verbose_name_plural': 'Subscription histories',
                'db_table': 'subscription_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='idx_sub_org_status'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['subscription', 'billing_period_start'], name='idx_bill_sub_period'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['payment_status'], name='idx_bill_status'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['payment_due_date'], name='idx_bill_due_date'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['subscription', 'change_type'], name='idx_subhist_sub_type'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['created_at'], name='idx_subhist_created'),
        ),
    ]
