# Generated by Django 5.2.6 on 2025-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_rules', '0002_subscription_billingrecord_subscriptionhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='additional_staff',
            field=models.TextField(blank=True, help_text='Other staff information'),
        ),
        migrations.AddField(
            model_name='judge',
            name='apprentices',
            field=models.TextField(blank=True, help_text='Names of apprentices or interns (one per line)'),
        ),
        migrations.AddField(
            model_name='judge',
            name='clerk_email',
            field=models.EmailField(blank=True, help_text="Clerk's email address", max_length=254),
        ),
        migrations.AddField(
            model_name='judge',
            name='clerk_name',
            field=models.CharField(blank=True, help_text="Name of judge's law clerk", max_length=255),
        ),
        migrations.AddField(
            model_name='judge',
            name='clerk_phone',
            field=models.CharField(blank=True, help_text="Clerk's phone number", max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='clerk_room',
            field=models.CharField(blank=True, help_text="Clerk's room/office number", max_length=100),
        ),
    ]
