# Generated by Django 5.2.6 on 2025-10-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocCourt',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'POC Court',
                'verbose_name_plural': 'POC Courts',
                'db_table': 'poc_court',
            },
        ),
        migrations.CreateModel(
            name='PocChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_kind', models.CharField(choices=[('rule_node', 'Rule Node'), ('judge_proc_node', 'Judge Procedure'), ('judge', 'Judge')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=10)),
                ('old_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('new_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('diff_text', models.TextField(blank=True, null=True)),
                ('diff_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'POC Change Event',
                'verbose_name_plural': 'POC Change Events',
                'db_table': 'poc_change_event',
                'indexes': [models.Index(fields=['entity_kind', 'entity_id'], name='poc_change__entity__91b771_idx'), models.Index(fields=['detected_at'], name='poc_change__detecte_f9dfd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PocJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('courtroom', models.CharField(blank=True, max_length=50, null=True)),
                ('chambers', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='court_rules.poccourt')),
            ],
            options={
                'verbose_name': 'POC Judge',
                'verbose_name_plural': 'POC Judges',
                'db_table': 'poc_judge',
            },
        ),
        migrations.CreateModel(
            name='PocJudgeProcNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=20)),
                ('ordinal', models.IntegerField(default=0)),
                ('heading', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('normalized_text_hash', models.CharField(blank=True, max_length=64)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='court_rules.pocjudge')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='court_rules.pocjudgeprocnode')),
            ],
            options={
                'verbose_name': 'POC Judge Procedure',
                'verbose_name_plural': 'POC Judge Procedures',
                'db_table': 'poc_judge_proc_node',
            },
        ),
        migrations.CreateModel(
            name='PocRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('rule_node', 'Rule Node'), ('judge_proc_node', 'Judge Procedure')], max_length=20)),
                ('source_id', models.BigIntegerField()),
                ('requirement_type', models.CharField(choices=[('page_limit', 'Page Limit'), ('word_limit', 'Word Limit'), ('formatting', 'Formatting'), ('deadline', 'Deadline'), ('filing', 'Filing'), ('service', 'Service'), ('content', 'Content'), ('procedural', 'Procedural')], max_length=20)),
                ('requirement_text', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'POC Requirement',
                'verbose_name_plural': 'POC Requirements',
                'db_table': 'poc_requirement',
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='poc_require_source__b3808e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PocComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('court_code', models.CharField(max_length=20)),
                ('case_metadata', models.JSONField()),
                ('overall_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning')], max_length=10)),
                ('violations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='court_rules.pocjudge')),
            ],
            options={
                'verbose_name': 'POC Compliance Check',
                'verbose_name_plural': 'POC Compliance Checks',
                'db_table': 'poc_compliance_check',
                'indexes': [models.Index(fields=['court_code'], name='poc_complia_court_c_ca1c44_idx'), models.Index(fields=['check_date'], name='poc_complia_check_d_a1163b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PocRuleNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('node_type', models.CharField(choices=[('rule', 'Rule'), ('section', 'Section'), ('subsection', 'Subsection'), ('clause', 'Clause')], max_length=20)),
                ('ordinal', models.IntegerField(default=0)),
                ('heading', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('normalized_text_hash', models.CharField(blank=True, max_length=64)),
                ('effective_from', models.DateTimeField(auto_now_add=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='court_rules.poccourt')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='court_rules.pocrulenode')),
            ],
            options={
                'verbose_name': 'POC Rule Node',
                'verbose_name_plural': 'POC Rule Nodes',
                'db_table': 'poc_rule_node',
                'indexes': [models.Index(fields=['court', 'rule_code'], name='poc_rule_no_court_i_6b9568_idx'), models.Index(fields=['effective_from', 'effective_to'], name='poc_rule_no_effecti_805218_idx')],
            },
        ),
    ]
