# Generated by Django 5.2.6 on 2025-11-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_rules', '0003_judge_additional_staff_judge_apprentices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='executive_law_clerk',
            field=models.CharField(blank=True, help_text='Executive Law Clerk name', max_length=255),
        ),
        migrations.AddField(
            model_name='judge',
            name='judicial_assistant',
            field=models.CharField(blank=True, help_text='Judicial Assistant name', max_length=255),
        ),
        migrations.AlterField(
            model_name='judge',
            name='additional_staff',
            field=models.TextField(blank=True, help_text='Other staff information (Court Reporter, etc.)'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='apprentices',
            field=models.TextField(blank=True, help_text='Names of law clerks, apprentices or interns (one per line)'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='clerk_email',
            field=models.EmailField(blank=True, help_text="Courtroom Deputy's email address", max_length=254),
        ),
        migrations.AlterField(
            model_name='judge',
            name='clerk_name',
            field=models.CharField(blank=True, help_text='Name of Courtroom Deputy', max_length=255),
        ),
        migrations.AlterField(
            model_name='judge',
            name='clerk_phone',
            field=models.CharField(blank=True, help_text="Courtroom Deputy's phone number", max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='clerk_room',
            field=models.CharField(blank=True, help_text="Courtroom Deputy's room/office number", max_length=100),
        ),
    ]
