# Generated by Django 5.2.6 on 2025-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_rules', '0004_judge_executive_law_clerk_judge_judicial_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='court_reporter_name',
            field=models.CharField(blank=True, help_text="Court Reporter's name", max_length=255),
        ),
        migrations.AddField(
            model_name='judge',
            name='court_reporter_phone',
            field=models.CharField(blank=True, help_text="Court Reporter's phone number", max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='court_reporter_room',
            field=models.CharField(blank=True, help_text="Court Reporter's room/office number", max_length=100),
        ),
        migrations.AddField(
            model_name='judge',
            name='executive_law_clerk_phone',
            field=models.CharField(blank=True, help_text="Executive Law Clerk's phone number", max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='executive_law_clerk_room',
            field=models.CharField(blank=True, help_text="Executive Law Clerk's room/office number", max_length=100),
        ),
        migrations.AddField(
            model_name='judge',
            name='judicial_assistant_phone',
            field=models.CharField(blank=True, help_text="Judicial Assistant's phone number", max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='judicial_assistant_room',
            field=models.CharField(blank=True, help_text="Judicial Assistant's room/office number", max_length=100),
        ),
        migrations.AlterField(
            model_name='judge',
            name='additional_staff',
            field=models.TextField(blank=True, help_text='Additional staff information (legacy field)'),
        ),
    ]
